name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'coral-dev'

env:
  KUBECONFIG: NONPROD

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Set environment
        run: echo "KUBECONFIG=PROD" >> $GITHUB_ENV

      - name: Check if we are running in Prod or PreProd
        run: echo "${{ env.KUBECONFIG }}"



      # - name: Compile
      #   if: ${{ github.event.inputs.environment != 'coral' }} # Non-Prod
      #   run: |
      #     echo running nonprod step

      # - name: Compile Prod
      #   if: ${{ github.event.inputs.environment == 'coral' }} # Prod
      #   run: |
      #     echo running prod step
