name: ENVTest 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'coral-uat'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Print environment
        run: echo building.......

  deploy-uat:
    runs-on: 'ubuntu-latest'
    if: ${{ github.event.inputs.environment == 'coral-uat' }}
    environment: 'uat'
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Print environment
        run: echo deploying [uat].......

  deploy-prod:
    runs-on: 'ubuntu-latest'
    if: ${{ github.event.inputs.environment == 'coral' }}
    environment: 'prd'
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Print environment
        run: echo deploying [prd].......
