name: ENVTest 

on:
  push: 
    branches: 
      - master

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'coral-uat'
      run_terraform:
        description: Should we run the terraform step
        type: boolean
        default: true   
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: uat
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Import environment variables from a file
        id: import-env        
        shell: bash
        run: |
          # obtain environment specific values
          cat wf-config.json | jq -r '.environments.uat | to_entries | map("\(.key)=\(.value|tostring)") | .[]' > tmp.env
          # variable substituion
          sed -i 's/AZURE_CLIENT_SECRET/${{ secrets.AZURE_CLIENT_SECRET }}/g' wf-config.json          
          while read line; do
            echo "$line"
            echo "$line" >> $GITHUB_ENV
          done < tmp.env
          cat tmp.env

      - name: Print Env
        run: | 
          printenv 
          echo $AZURE_CLIENT_SECRET | base64

      # - name: A
      #   if: ${{ github.event.inputs.run_terraform == true }}
      #   run: echo ${{ github.event.inputs.run_terraform }}

      # - name: B
      #   if: ${{ github.event.inputs.run_terraform == 'true' }}
      #   run: echo ${{ github.event.inputs.run_terraform }}

  # deploy-uat:
  #   runs-on: 'ubuntu-latest'
  #   if: ${{ github.event.inputs.environment == 'coral-uat' }}
  #   environment: 'uat'
  #   steps:

  #     - name: Checkout
  #       uses: actions/checkout@v1

  #     - name: Print environment
  #       run: echo deploying [uat].......

  # deploy-prod:
  #   runs-on: 'ubuntu-latest'
  #   if: ${{ github.event.inputs.environment == 'coral' }}
  #   environment: 'prd'
  #   steps:

  #     - name: Checkout
  #       uses: actions/checkout@v1

  #     - name: Print environment
  #       run: echo deploying [prd].......
