name: IfElseTest
description: Checks If/else

on:
  # workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'coral-dev'

env:
  KUBECONFIG: NONPROD

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # - name: Run a one-line script
      #   run: echo Hello, world!

      # - name: Print environment
      #   run: echo "${{ env.KUBECONFIG }}"
        
      # - name: Set environment
      #   run: echo "KUBECONFIG=PROD" >> $GITHUB_ENV



      - name: Set correct environment variables
        if: ${{ github.event.inputs.environment != 'coral' }} # Non Prod
        env:
          KC: ${{ secrets.KUBECONFIG }}
        run: |
          echo "KC=${KC}" >> $GITHUB_ENV
          printenv > secrets.txt

      - name: Print environment
        run: echo "${{ env.KC }}"

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2


      # - name: Compile
      #   if: ${{ github.event.inputs.environment != 'coral' }} # Non-Prod
      #   run: |
      #     echo running nonprod step

      # - name: Compile Prod
      #   if: ${{ github.event.inputs.environment == 'coral' }} # Prod
      #   run: |
      #     echo running prod step
