name: ENVTest 
description: Tests Environments feature

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'coral-dev'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Print environment
        run: echo building.......

  deploy-dev:
    runs-on: 'ubuntu-latest'
    environment: 'uat'
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Print environment
        run: echo deploying [uat].......

  deploy-prod:
    runs-on: 'ubuntu-latest'
    environment: 'prd'
    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Print environment
        run: echo deploying [prd].......
        